### ISSUE TITLE
different results from the original darknet

### ISSUE THREAD

**Issue by zjcbatman** [ayooshkathuria/YOLO_v3_tutorial_from_scratch#9] opened 2018-04-27 12:04 UTC
HI, I have run the code and the original darknet with the same image,but i got different results. I cannot understand because the cfg file and weights file are all the same.
This is the result running the original darknet:
![predictions](https://user-images.githubusercontent.com/16145164/39361617-ed6f880e-4a55-11e8-99e1-4ef760c89213.png)

This is the result running this code:
![det_000000](https://user-images.githubusercontent.com/16145164/39361675-1bbbca1a-4a56-11e8-8cc9-a4ef440b584a.JPEG)
why??

**Comment by ayooshkathuria** [comment] 2018-04-27 12:16
Beat me too. Honestly, even for the other repos of YOLO v2 I had come across, they couldn't match the accuracy of darknet, (the mAP was 76.8 using exactly the same cfg and weights file, whereas it was 78.6 with the original darknet). I haven't dwelt too much into the issue. Even while training from scratch they couldn't achieve more than 75 mAP. 

I have used billinear umpsampling in the upsample layer. Maybe the original repo has something else. Maybe nearest neighbour sampling. So, you can find the code responsible for that in the function `create_modules` in util.py. 

Also, you can try to decrease the objectness_confidence threshold. from 0.5 to something like 0.3.

**Comment by ayooshkathuria** [comment] 2018-04-27 12:26
Can you send me the pic. I'll just try looking at the output feature map and inspect the values over at the weekend. Just upload it in a comment here.

**Comment by zjcbatman** [comment] 2018-04-27 12:27
![000000](https://user-images.githubusercontent.com/16145164/39362521-576705e0-4a59-11e8-9e70-81e775720c63.JPEG)

**Comment by ayooshkathuria** [comment] 2018-04-27 12:29
Thank you for pointing the flaw out. I'll try to look into it.

**Comment by ayooshkathuria** [comment] 2018-04-27 12:31
Could you think of a reason why this might be happening? Do you think if it's a pytorch thing. Maybe some way darknet is different from pytorch?

**Comment by zjcbatman** [comment] 2018-04-27 12:33
My pleasure. I think it's great to translate the darknet into pytorch. I have not got any idea about this issue now. I will look into your code and darknet to see whether there is some difference

**Comment by ayooshkathuria** [comment] 2018-04-27 12:35
Weird stuff. This is the result on my mac, (I ran it on CPU since I don't have access to a GPU at home)

![image](https://user-images.githubusercontent.com/22730263/39362848-893135c8-4a45-11e8-87c6-496f0cb8ac2c.png)

confidence 0.25

**Comment by ayooshkathuria** [comment] 2018-04-27 12:38
Please check how upsampling is done in darknet for sure, coz that's what i think may be the weak link.

**Comment by zjcbatman** [comment] 2018-04-27 12:38
I also ran it on cpu. ok, thx.

**Comment by ayooshkathuria** [comment] 2018-04-27 12:51
HEY!!!!!!! LOOK AT THIS BEAUTY!

![image](https://user-images.githubusercontent.com/22730263/39363343-9676455a-4a47-11e8-9871-c898dd7e4e1d.png)

I commented out the NMS code. So, it means, I've screwed up somewhere in NMS code and that problem didn't show it's head until your example came. Thank you man (or woman?)

I'll try to solve it as soon as possible.

**Comment by zjcbatman** [comment] 2018-04-27 13:31
oh, that's wonderful !

**Comment by zjcbatman** [comment] 2018-04-27 13:42
Have you found what's wrong with your NMS code?

**Comment by ayooshkathuria** [comment] 2018-04-27 13:47
Nope. Will look into that over the weekend.

**Comment by zjcbatman** [comment] 2018-04-27 15:14
hi, I have found your small mistake. In the function bbox_iou in util.py, 
`inter_area = (inter_rect_x2 - inter_rect_x1 + 1) * (inter_rect_y2 - inter_rect_y1 + 1)`
you have forgot that either two may smaller than 0, i think you should change this to
` w = np.maximum(inter_rect_x2 - inter_rect_x1 + 1, 0)
h = np.maximum(inter_rect_y2 - inter_rect_y1 + 1, 0)
    inter_area = w * h`

**Comment by ayooshkathuria** [comment] 2018-04-27 15:17
Does that solve the detection problem we were having?

**Comment by zjcbatman** [comment] 2018-04-27 15:53
But I found that there are still some problems about this issue.
![det_000003](https://user-images.githubusercontent.com/16145164/39371951-b5ac8f64-4a75-11e8-86b5-f066ec9de5db.JPEG)
![predictions](https://user-images.githubusercontent.com/16145164/39371968-c1e51918-4a75-11e8-8a18-ab3f1866733b.png)
and i commented the NMS code, got this
![det_000003](https://user-images.githubusercontent.com/16145164/39372079-058f035e-4a76-11e8-8332-2f5ff4419083.JPEG)
so now there is nothing wrong with NMS, any other problem?

**Comment by ayooshkathuria** [comment] 2018-04-27 16:01
NMS code commented with your fix. 

![image](https://user-images.githubusercontent.com/22730263/39372523-4196a4f6-4a62-11e8-857e-501e73a43796.png)

**Comment by ayooshkathuria** [comment] 2018-04-27 16:02
I'm just wondering which of the run cases causes the negative value of the line `(inter_rect_x2 - inter_rect_x1 + 1)` cause that seems to be the problem!!!

**Comment by ayooshkathuria** [comment] 2018-04-27 18:08
It's a bit crazy I can register all detections at 0.5 confidence at 448 resolution, but miss 3 when I switch the resolution to 416, the native resolution. 

But hey, look at this, https://groups.google.com/forum/#!topic/darknet/JTNuaTtpm94, where joseph redmon, originally talks about how implementation of YOLO is CPU is different. Maybe the optimisations introduced by PyTorch are pushing the scores of the three missed planes to zero.

**Comment by zjcbatman** [comment] 2018-04-28 02:12
Oh, I just can't understand why the resolution could affect the result.

**Comment by zjcbatman** [comment] 2018-04-28 02:51
I got one obvious example.
![000015](https://user-images.githubusercontent.com/16145164/39391155-bac95d0e-4ad1-11e8-9869-8a966457c314.JPEG)
I tested the code on this pic, **but the result was no plane is on this pic.**

However, in the original darknet, I got this:
![predictions](https://user-images.githubusercontent.com/16145164/39391170-f48acaaa-4ad1-11e8-9da5-51be245b4911.png)

**Comment by zjcbatman** [comment] 2018-04-28 05:48
ok, I am looking forward to that

**Comment by ayooshkathuria** [comment] 2018-04-28 08:40
I tried to run the code on a GPU, and the problem persists. This means the issue is with my implementation and not the optimizations done by the underlying libraries.

**Comment by ayooshkathuria** [comment] 2018-04-28 22:59
So, I finally got the error, I think. The fix works on all of the images you have provided. This is the intermediate result (I wrote custom code to test my solution) for the last image that you have provided. 

![image](https://user-images.githubusercontent.com/22730263/39401556-5367f956-4b65-11e8-8d03-0adc5b172eef.png)

## The problem 

So, looking at darknet I realized that the way an input image is resized to 416 x 416 is different from what I was doing. In darknet, the image is resized keeping the aspect ratio intact, and padding the remaining area. For example, when your image, being resized to 416 x 416 will look like this

![image](https://user-images.githubusercontent.com/22730263/39401564-91c50a54-4b65-11e8-8d64-5d0a5f654476.png). 

I had simply resized it isotropically using `cv2.resize` and writing a function that does something like above did solve the issue. I'll be integrated changes into the repo in the next day or two. Currently, the bounding box drawing code is written in accordance with isotropic resizing and I'll have to change that, and will push the fix to the repo soon.

**Comment by zjcbatman** [comment] 2018-04-29 00:34
Great! I think that will solve this issue! Thanks!

**Comment by ayooshkathuria** [comment] 2018-04-29 21:40
I've pushed the changes. Do let me know whether the issues are resolved now or not.

**Comment by ayooshkathuria** [comment] 2018-04-29 23:11
I have pushed the changes. Please check whether your issues were resolved or not. And yes, the code will work only with PyTorch 0.4, which is available on pip and conda channels now.

**Comment by zjcbatman** [comment] 2018-04-30 02:27
I have tested on my dataset and I think this time the issue was totally solved !

**Comment by ayooshkathuria** [comment] 2018-04-30 07:11
All right. I'm closing this issue then. Thanks for your time in pointing out and helping solve this issue.

**Closed by ayooshkathuria** 2018-04-30 07:11 UTC

**Comment by priyankasin** [comment] 2019-03-13 09:14
I have run your code and darknet_alexey with the same images and same weights but I got different results. Earlier you had the same issue and you resolve this issue, but I still got the error with your updated repo. can you please help me to resolve the issue?
